"""rename address

Revision ID: f4fe02a7e9c2
Revises: c38fb269a285
Create Date: 2024-06-28 23:51:19.276643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4fe02a7e9c2'
down_revision = 'c38fb269a285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name='location')
    # op.drop_column('departments', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
    op.alter_column('departments', 'location', new_column_name='address')
    # ### end Alembic commands ###
